//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utils.Resources.GeneralMessages", typeof(GeneralMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente no registrado..
        /// </summary>
        public static string AgentNotFound {
            get {
                return ResourceManager.GetString("AgentNotFound", resourceCulture);
            }
        }


        public static string RecordNotFound
        {
            get
            {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }

        public static string NotDeleteRelations
        {
            get
            {
                return ResourceManager.GetString("NotDeleteRelations", resourceCulture);
            }
        }

        public static string ReadyRecord
        {
            get
            {
                return ResourceManager.GetString("ReadyRecord", resourceCulture);
            }
        }

        public static string RecordAsignated
        {
            get
            {
                return ResourceManager.GetString("RecordAsignated", resourceCulture);
            }
        }

        public static string NotRecords
        {
            get
            {
                return ResourceManager.GetString("NotRecords", resourceCulture);
            }
        }

        public static string RolNotFound
        {
            get
            {
                return ResourceManager.GetString("RolNotFound", resourceCulture);
            }
        }

        public static string UserNotFound
        {
            get
            {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        public static string IncorrectPassword
        {
            get
            {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }

        public static string ReadyOption
        {
            get
            {
                return ResourceManager.GetString("ReadyOption", resourceCulture);
            }
        }

        public static string PasswordEquals
        {
            get
            {
                return ResourceManager.GetString("PasswordEquals", resourceCulture);
            }
        }

        public static string Block
        {
            get
            {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        public static string NoExistOption
        {
            get
            {
                return ResourceManager.GetString("NoExistOption", resourceCulture);
            }
        }
        public static string RolAsigned
        {
            get
            {
                return ResourceManager.GetString("RolAsigned", resourceCulture);
            }
        }



        public static string ReadyAcces
        {
            get
            {
                return ResourceManager.GetString("ReadyAcces", resourceCulture);
            }
        }

        public static string AccesNotFound
        {
            get
            {
                return ResourceManager.GetString("AccesNotFound", resourceCulture);
            }
        }



        public static string ReadyUser
        {
            get
            {
                return ResourceManager.GetString("ReadyUser", resourceCulture);
            }
        }

        public static string ReadyRol
        {
            get
            {
                return ResourceManager.GetString("ReadyRol", resourceCulture);
            }
        }
        public static string RolUserNotFound
        {
            get
            {
                return ResourceManager.GetString("RolUserNotFound", resourceCulture);
            }
        }

        public static string InactiveUser
        {
            get
            {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }

        public static string UserInactive
        {
            get
            {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }

        public static string DiferentPassword
        {
            get
            {
                return ResourceManager.GetString("DiferentPassword", resourceCulture);
            }
        }

        public static string NoEmail
        {
            get
            {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }

        public static string Host
        {
            get
            {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }

        public static string Port
        {
            get
            {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }

        public static string From
        {
            get
            {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }

        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string ValidationEmailSubject
        {
            get
            {
                return ResourceManager.GetString("ValidationEmailSubject", resourceCulture);
            }
        }

        public static string ValidationEmailBody
        {
            get
            {
                return ResourceManager.GetString("ValidationEmailBody", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to El agente no tiene matriculado ningun Esquema para este periodo Agente :.
        /// </summary>
        public static string AgentWithoutScheme {
            get {
                return ResourceManager.GetString("AgentWithoutScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede crear una nueva solicitud porque en este momento se encuentra una en proceso para el mismo día..
        /// </summary>
        public static string ApplicationExist {
            get {
                return ResourceManager.GetString("ApplicationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró configuración de datos para la fecha indicada..
        /// </summary>
        public static string AutomaticChargeTiesConfigData {
            get {
                return ResourceManager.GetString("AutomaticChargeTiesConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha cumplido el tiempo de frecuencia establecido, intente mas tarde..
        /// </summary>
        public static string AutomaticChargeTiesFrecuency {
            get {
                return ResourceManager.GetString("AutomaticChargeTiesFrecuency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superó el número máximo de intentos para ejecución de job..
        /// </summary>
        public static string AutomaticChargeTiesLoadRetry {
            get {
                return ResourceManager.GetString("AutomaticChargeTiesLoadRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una carga para la fecha indicada..
        /// </summary>
        public static string AutomaticChargeTiesRegisterExists {
            get {
                return ResourceManager.GetString("AutomaticChargeTiesRegisterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de la transferencia no concuerda con la sumatoria de la carga..
        /// </summary>
        public static string BalanceDifferent {
            get {
                return ResourceManager.GetString("BalanceDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto calculado no puede ser cero (0)..
        /// </summary>
        public static string CalculateAmountZero {
            get {
                return ResourceManager.GetString("CalculateAmountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede realizar la carga. Existe al menos un pago en esa fecha..
        /// </summary>
        public static string CantChargePay {
            get {
                return ResourceManager.GetString("CantChargePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga existente, ¿Desea sobreescribir?..
        /// </summary>
        public static string ChargeOverWrite {
            get {
                return ResourceManager.GetString("ChargeOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto no encontrado..
        /// </summary>
        public static string ConceptNoFound {
            get {
                return ResourceManager.GetString("ConceptNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se almacenó el registro satisfactoriamente..
        /// </summary>
        public static string CreateRecord {
            get {
                return ResourceManager.GetString("CreateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro eliminar el extracto @NumeroCuenta@, por favor vuelva a intentarlo..
        /// </summary>
        public static string DeleteFileBlobFailed {
            get {
                return ResourceManager.GetString("DeleteFileBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el movimiento para eliminar..
        /// </summary>
        public static string DeleteFileDataConciliationError {
            get {
                return ResourceManager.GetString("DeleteFileDataConciliationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logró desplublicar el extracto @NumeroCuenta@, por favor vuelva a intentarlo..
        /// </summary>
        public static string DeleteFileFTPFailed {
            get {
                return ResourceManager.GetString("DeleteFileFTPFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminó el registro satisfactoriamente..
        /// </summary>
        public static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su usario no tiene permiso para cambiar a solicitud a este estado..
        /// </summary>
        public static string DenegadeAgent {
            get {
                return ResourceManager.GetString("DenegadeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo viene vacio..
        /// </summary>
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error interno..
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Acme de integridad de las garantias..Numero :{0}.
        /// </summary>
        public static string ErrorConfigurationWarranty {
            get {
                return ResourceManager.GetString("ErrorConfigurationWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agente {0} no esta configurado para la garantia  número {1}.
        /// </summary>
        public static string ErrorNotAgentWarranty {
            get {
                return ResourceManager.GetString("ErrorNotAgentWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible publicar el archivo en el portal..
        /// </summary>
        public static string ErrorPublicPortalFileXmFull {
            get {
                return ResourceManager.GetString("ErrorPublicPortalFileXmFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha enviado parametro de números de garantia por liberar Numero {0}.
        /// </summary>
        public static string ErrorWarrantyEmpty {
            get {
                return ResourceManager.GetString("ErrorWarrantyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La garantia  tiene Valores Aplicados pendientes  Numero {0}.
        /// </summary>
        public static string ErrorWarrantyNotApplied {
            get {
                return ResourceManager.GetString("ErrorWarrantyNotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de garantia no Existe Numero {0}.
        /// </summary>
        public static string ErrorWarrantyNotExist {
            get {
                return ResourceManager.GetString("ErrorWarrantyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una conciliación realizada en ese rango de fechas {0} - {1}. Presione Guardar nuevamente para remplazar la conciliación actual..
        /// </summary>
        public static string ExistConciliation {
            get {
                return ResourceManager.GetString("ExistConciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros para el vencimiento..
        /// </summary>
        public static string ExpirationNotData {
            get {
                return ResourceManager.GetString("ExpirationNotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo {0} generado con éxito en la ruta {1}.
        /// </summary>
        public static string FileGenerated {
            get {
                return ResourceManager.GetString("FileGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha Inicial no puede ser mayor a la final.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible eliminar la carga de vencimiento..
        /// </summary>
        public static string loadExirationDeleteError {
            get {
                return ResourceManager.GetString("loadExirationDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo cargado éxitosamente..
        /// </summary>
        public static string LoadFileMulticashSuccess {
            get {
                return ResourceManager.GetString("LoadFileMulticashSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no tiene Valor solicitado..
        /// </summary>
        public static string NoRequstValue {
            get {
                return ResourceManager.GetString("NoRequstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrija las garantias con datos erróneos y quite las que alcanzo a grabar.
        /// </summary>
        public static string NoSaveWarranty {
            get {
                return ResourceManager.GetString("NoSaveWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay saldo disponible suficiente en la cuenta custodia para esta aplicacion..
        /// </summary>
        public static string NotBalance {
            get {
                return ResourceManager.GetString("NotBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay saldo para la solicitud..
        /// </summary>
        public static string NotBalanceForApplication {
            get {
                return ResourceManager.GetString("NotBalanceForApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el registro de configuración de medios magnéticos..
        /// </summary>
        public static string NotDeleteMediaMagnetic {
            get {
                return ResourceManager.GetString("NotDeleteMediaMagnetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la solicitud por el estado en el que se encuentra..
        /// </summary>
        public static string NotDeleteStatus {
            get {
                return ResourceManager.GetString("NotDeleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de excel es incorrecto.
        /// </summary>
        public static string NotFormatted {
            get {
                return ResourceManager.GetString("NotFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay valores congelados  ya aplicados que cumplan con las reglas de  este negativo.
        /// </summary>
        public static string NotFrozenValue {
            get {
                return ResourceManager.GetString("NotFrozenValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se envió la notificación éxitosamente..
        /// </summary>
        public static string NotificationDelivery {
            get {
                return ResourceManager.GetString("NotificationDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al enviar notificación..
        /// </summary>
        public static string NotificationFailed {
            get {
                return ResourceManager.GetString("NotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible eliminar la carga de vencimentos dado que existe por lo menos un registro de pago en estado aplicado..
        /// </summary>
        public static string NotRemoveExpirationLoad {
            get {
                return ResourceManager.GetString("NotRemoveExpirationLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agente tiene configurado otro esquema. Agente:.
        /// </summary>
        public static string NotScheme {
            get {
                return ResourceManager.GetString("NotScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen registros no almacenados, por lo tanto no es posible enviar la notificación..
        /// </summary>
        public static string NotSendNotification {
            get {
                return ResourceManager.GetString("NotSendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación fallida..
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado el cierre TIE, los siguientes agentes  están en estado pendiente..
        /// </summary>
        public static string ProblemsClosed {
            get {
                return ResourceManager.GetString("ProblemsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Código: {1}.
        /// </summary>
        public static string ProcessBankCode {
            get {
                return ResourceManager.GetString("ProcessBankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo publicado correctamente en el portal..
        /// </summary>
        public static string PublicPortalFileXmFull {
            get {
                return ResourceManager.GetString("PublicPortalFileXmFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor valide que exista la ruta base para la publicación del archivo del agente {0}..
        /// </summary>
        public static string PublishFileCheckExistsPath {
            get {
                return ResourceManager.GetString("PublishFileCheckExistsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otra conciliacion con fechas {0}.
        /// </summary>
        public static string ReadyConciliation {
            get {
                return ResourceManager.GetString("ReadyConciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El vencimiento ya está en estado Precierre Aprobado..
        /// </summary>
        public static string readyPreclose {
            get {
                return ResourceManager.GetString("readyPreclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible eliminar el registro porque no se encuentra almacenado..
        /// </summary>
        public static string RecordNotDeleted {
            get {
                return ResourceManager.GetString("RecordNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro(s) eliminado(s) exitosamente..
        /// </summary>
        public static string RecordsDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RecordsDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los siguientes registros ya fueron almacenados previamente. Verifique la información..
        /// </summary>
        public static string RecordsErrorStored {
            get {
                return ResourceManager.GetString("RecordsErrorStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros almacenados exitosamente..
        /// </summary>
        public static string RecordsSuccessfullyStored {
            get {
                return ResourceManager.GetString("RecordsSuccessfullyStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} el archivo multicash para el banco {1} y el negocio {2}.
        /// </summary>
        public static string ResultMulticashFileProcess {
            get {
                return ResourceManager.GetString("ResultMulticashFileProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las siguientes líneas ya tienen transacciones realizadas:.
        /// </summary>
        public static string ReturnStatusPendingError {
            get {
                return ResourceManager.GetString("ReturnStatusPendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos para la fecha..
        /// </summary>
        public static string ReturnStatusPendingErrorDate {
            get {
                return ResourceManager.GetString("ReturnStatusPendingErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha devuelto el cierre con éxito..
        /// </summary>
        public static string ReturnStatusPendingSuccessful {
            get {
                return ResourceManager.GetString("ReturnStatusPendingSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El periodo que intenta insertar es menor al último periodo abierto del agente..
        /// </summary>
        public static string SchemaAgentCreateValidationOldPeriod {
            get {
                return ResourceManager.GetString("SchemaAgentCreateValidationOldPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible registrar el esquema porque el agente ya tiene cargada una garantía para la vigencia ingresada..
        /// </summary>
        public static string SchemaAgentCreateWarrantyExpiration {
            get {
                return ResourceManager.GetString("SchemaAgentCreateWarrantyExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentran registro(s)..
        /// </summary>
        public static string SchemaAgentDeleteError {
            get {
                return ResourceManager.GetString("SchemaAgentDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminó el registro para el esquema con Agente {0}-{1}, Esquema {2} y periodo {3}.
        /// </summary>
        public static string SchemaAgentDeleteSuccess {
            get {
                return ResourceManager.GetString("SchemaAgentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible modificar el esquema porque ya tiene cargada una garantía para el periodo seleccionado..
        /// </summary>
        public static string SchemaAgentEditValidation {
            get {
                return ResourceManager.GetString("SchemaAgentEditValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible modificar el esquema porque el periodo seleccionado ya se encuentra cerrado..
        /// </summary>
        public static string SchemaAgentEditValidationClosePeriod {
            get {
                return ResourceManager.GetString("SchemaAgentEditValidationClosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo registrar el esquema..
        /// </summary>
        public static string SchemaAgentFail {
            get {
                return ResourceManager.GetString("SchemaAgentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el registro para el esquema con Agente {0}-{1}, Esquema {2} y periodo {3} porque está asociado a un cálculo de garantía..
        /// </summary>
        public static string SchemaAgentHasLoad {
            get {
                return ResourceManager.GetString("SchemaAgentHasLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agente ya tiene registrado un esquema para este periodo..
        /// </summary>
        public static string SchemaAgentRegistryExists {
            get {
                return ResourceManager.GetString("SchemaAgentRegistryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha registrado correctamente el esquema..
        /// </summary>
        public static string SchemaAgentSuccess {
            get {
                return ResourceManager.GetString("SchemaAgentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar esquema..
        /// </summary>
        public static string SchemaAgentUpdateFail {
            get {
                return ResourceManager.GetString("SchemaAgentUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado correctamente el esquema..
        /// </summary>
        public static string SchemaAgentUpdateSuccess {
            get {
                return ResourceManager.GetString("SchemaAgentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible modificar el esquema porque el agente ya tiene cargada una garantía para la vigencia ingresada..
        /// </summary>
        public static string SchemaAgentUpdateWarrantyExpiration {
            get {
                return ResourceManager.GetString("SchemaAgentUpdateWarrantyExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente no tiene asociado esquema para el período..
        /// </summary>
        public static string SchemeAgentNotFound {
            get {
                return ResourceManager.GetString("SchemeAgentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación enviada con éxito..
        /// </summary>
        public static string SentNotification {
            get {
                return ResourceManager.GetString("SentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible eliminar el/los registro(s) porque existe un vencimiento superior al actual..
        /// </summary>
        public static string SuperiorMaturity {
            get {
                return ResourceManager.GetString("SuperiorMaturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso realizado éxitosamente..
        /// </summary>
        public static string SussefullyProcess {
            get {
                return ResourceManager.GetString("SussefullyProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el movimiento para editar..
        /// </summary>
        public static string UpdateFileDataConciliationError {
            get {
                return ResourceManager.GetString("UpdateFileDataConciliationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se actualizó el registro satisfactoriamente..
        /// </summary>
        public static string UpdateRecord {
            get {
                return ResourceManager.GetString("UpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible actualizar la entidad bancaria, por favor valide los campos Código banco, Código ACH, Sector superintendencia..
        /// </summary>
        public static string ValidateBank {
            get {
                return ResourceManager.GetString("ValidateBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El banco seleccionado no puede ser utilizado para procesar la información..
        /// </summary>
        public static string ValidateBankNotAvaible {
            get {
                return ResourceManager.GetString("ValidateBankNotAvaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de cuenta del adjunto no coincide con el ingresado en el formulario..
        /// </summary>
        public static string ValidateEqualAccountUploadBank {
            get {
                return ResourceManager.GetString("ValidateEqualAccountUploadBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una configuración con titulo de hoja {0}..
        /// </summary>
        public static string ValidateExistsSheetTitle {
            get {
                return ResourceManager.GetString("ValidateExistsSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo agente no corresponde a un agente existente..
        /// </summary>
        public static string ValidateFileTiesExistsAgent {
            get {
                return ResourceManager.GetString("ValidateFileTiesExistsAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo vencimiento no tiene el formato de fecha correcto (dd/MM/aaaa)..
        /// </summary>
        public static string ValidateFileTiesIsDateExpirationDate {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsDateExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo fecha final no tiene el formato de fecha correcto (dd/MM/aaaa)..
        /// </summary>
        public static string ValidateFileTiesIsDateFinalDate {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsDateFinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo fecha inicial no tiene el formato de fecha correcto (dd/MM/aaaa)..
        /// </summary>
        public static string ValidateFileTiesIsDateInitialDate {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsDateInitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo agente no puede estar vacío..
        /// </summary>
        public static string ValidateFileTiesIsEmptyAgent {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsEmptyAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo concepto no puede estar vacío..
        /// </summary>
        public static string ValidateFileTiesIsEmptyConcept {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsEmptyConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo vencimiento no puede estar vacío..
        /// </summary>
        public static string ValidateFileTiesIsEmptyExpirationDate {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsEmptyExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo fecha final no puede estar vacío..
        /// </summary>
        public static string ValidateFileTiesIsEmptyFinalDate {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsEmptyFinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo fecha inicial no puede estar vacío..
        /// </summary>
        public static string ValidateFileTiesIsEmptyInitialDate {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsEmptyInitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo tipo vencimiento no puede estar vacío..
        /// </summary>
        public static string ValidateFileTiesIsEmptyUploadType {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsEmptyUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo valor no puede estar vacío..
        /// </summary>
        public static string ValidateFileTiesIsEmptyValue {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo concepto no pertenece al tipo de archivo seleccionado..
        /// </summary>
        public static string ValidateFileTiesIsTiesConcept {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsTiesConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo tipo vencimiento no pertenece al tipo TIES..
        /// </summary>
        public static string ValidateFileTiesIsTiesUploadType {
            get {
                return ResourceManager.GetString("ValidateFileTiesIsTiesUploadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cierre no ha sido aprobado. No se puede devolver..
        /// </summary>
        public static string ValidateNoReadyApproveClose {
            get {
                return ResourceManager.GetString("ValidateNoReadyApproveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precierre no está aprobado. No se puede devolver..
        /// </summary>
        public static string ValidateNotReadyAprovedPreClose {
            get {
                return ResourceManager.GetString("ValidateNotReadyAprovedPreClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen valores pendientes por aplicar. ¿Desea continuar?..
        /// </summary>
        public static string ValidatePreClosePending {
            get {
                return ResourceManager.GetString("ValidatePreClosePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen valores en Saldo a Favor y Saldo a Favor Pendiente. ¿Desea continuar?..
        /// </summary>
        public static string ValidatePreClosePosBalance {
            get {
                return ResourceManager.GetString("ValidatePreClosePosBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cierre ya está aprobado solo. Se puede devolver..
        /// </summary>
        public static string ValidateReadyApproveClose {
            get {
                return ResourceManager.GetString("ValidateReadyApproveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precierre ya está aprobado. Solo se puede devolver..
        /// </summary>
        public static string ValidateReadyAprovePreClose {
            get {
                return ResourceManager.GetString("ValidateReadyAprovePreClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un inconveniente al guardar la informacion procesada..
        /// </summary>
        public static string ValidateSaveFailedUploadBank {
            get {
                return ResourceManager.GetString("ValidateSaveFailedUploadBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información cargada se guardó correctamente..
        /// </summary>
        public static string ValidateSaveSuccessUploadBank {
            get {
                return ResourceManager.GetString("ValidateSaveSuccessUploadBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La vigencia de la garantía no cubre el periodo a garantizar..
        /// </summary>
        public static string ValidateWarrantyValidity {
            get {
                return ResourceManager.GetString("ValidateWarrantyValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea actualizar la información almacenada para el fecha de aplicación seleccionada? Esto implica el borrado de la información almacenada previamente..
        /// </summary>
        public static string ValidDataCancellationSuppliesNotification {
            get {
                return ResourceManager.GetString("ValidDataCancellationSuppliesNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de aplicaciíon de pago debe ser igual al dia en curso..
        /// </summary>
        public static string ValidDateCancellationSuppliesNotification {
            get {
                return ResourceManager.GetString("ValidDateCancellationSuppliesNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos relacionados..
        /// </summary>
        public static string ValidDateCancellationSuppliesNotificationNotFound {
            get {
                return ResourceManager.GetString("ValidDateCancellationSuppliesNotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una sola Garantia.
        /// </summary>
        public static string VerySelected {
            get {
                return ResourceManager.GetString("VerySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenado Desde Admongar.
        /// </summary>
        public static string WarrantySucess {
            get {
                return ResourceManager.GetString("WarrantySucess", resourceCulture);
            }
        }
    }
}
