//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogProcessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogProcessMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utils.Resources.LogProcessMessages", typeof(LogProcessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación de garantias.
        /// </summary>
        public static string DeleteWarranties {
            get {
                return ResourceManager.GetString("DeleteWarranties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de proceso de solicitud de saldos de cuenta custodia.
        /// </summary>
        public static string EndProcessBalanceApplications {
            get {
                return ResourceManager.GetString("EndProcessBalanceApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de proceso de carga de archivo de garantias.
        /// </summary>
        public static string EndProcessChargeFileWarranties {
            get {
                return ResourceManager.GetString("EndProcessChargeFileWarranties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de Proceso de cargar vencimientos..
        /// </summary>
        public static string EndProcessLoadExpiration {
            get {
                return ResourceManager.GetString("EndProcessLoadExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finaliza carga de archivos multicash.
        /// </summary>
        public static string EndProcessMulticashFile {
            get {
                return ResourceManager.GetString("EndProcessMulticashFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de proceso de anulación de pago.
        /// </summary>
        public static string EndprocessPayAnulation {
            get {
                return ResourceManager.GetString("EndprocessPayAnulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de Proceso de reversión precierre.
        /// </summary>
        public static string EndProcessReverseClose {
            get {
                return ResourceManager.GetString("EndProcessReverseClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de proceso de reversión precierre.
        /// </summary>
        public static string EndProcessReversePreclose {
            get {
                return ResourceManager.GetString("EndProcessReversePreclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProcessMulticash.
        /// </summary>
        public static string ExceptionMulticash {
            get {
                return ResourceManager.GetString("ExceptionMulticash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar el archivo... ya existen estos numeros de garantia:.
        /// </summary>
        public static string FailChargeFileWarranty {
            get {
                return ResourceManager.GetString("FailChargeFileWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible realizar el proceso porque no se encontro parametros en la tabla GeneralParameters.
        /// </summary>
        public static string FailProcessMulticasFile {
            get {
                return ResourceManager.GetString("FailProcessMulticasFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar en base de datos origen los vencimientos..
        /// </summary>
        public static string GetLastExpiration {
            get {
                return ResourceManager.GetString("GetLastExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene Acceso a esta funcionalidad.
        /// </summary>
        public static string NotAccess {
            get {
                return ResourceManager.GetString("NotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay saldo disponible.
        /// </summary>
        public static string NotBalance {
            get {
                return ResourceManager.GetString("NotBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe cierre aprobado.
        /// </summary>
        public static string NotCloseApprove {
            get {
                return ResourceManager.GetString("NotCloseApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe precierre aprobado.
        /// </summary>
        public static string NotPrecloseApprove {
            get {
                return ResourceManager.GetString("NotPrecloseApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de consulta de vencimientos en origen..
        /// </summary>
        public static string ResultGetLastExpiration {
            get {
                return ResourceManager.GetString("ResultGetLastExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Proceso de cargar vencimientos..
        /// </summary>
        public static string StarProcessLoadExpiration {
            get {
                return ResourceManager.GetString("StarProcessLoadExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de lectura de archivos multicash..
        /// </summary>
        public static string StarReadMulticashFiles {
            get {
                return ResourceManager.GetString("StarReadMulticashFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio proceso de solicitud de saldos cuenta custodia.
        /// </summary>
        public static string StartProcessBalanceApplications {
            get {
                return ResourceManager.GetString("StartProcessBalanceApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de proceso de carga de archivo de garantias.
        /// </summary>
        public static string StartProcessChargeFileWarranties {
            get {
                return ResourceManager.GetString("StartProcessChargeFileWarranties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de carga de archivos multicash..
        /// </summary>
        public static string StartProcessMulticashFile {
            get {
                return ResourceManager.GetString("StartProcessMulticashFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de proceso de anulación de pago.
        /// </summary>
        public static string StartProcessPayAnulation {
            get {
                return ResourceManager.GetString("StartProcessPayAnulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de proceso de reversión precierre.
        /// </summary>
        public static string StartProcessReverseClose {
            get {
                return ResourceManager.GetString("StartProcessReverseClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de proceso de reversión de precierre.
        /// </summary>
        public static string StartProcessReversePreclose {
            get {
                return ResourceManager.GetString("StartProcessReversePreclose", resourceCulture);
            }
        }
    }
}
