//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationsFileLoad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationsFileLoad() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utils.Resources.ValidationsFileLoad", typeof(ValidationsFileLoad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga No realizada..El archivo tiene registros Invalidos.
        /// </summary>
        public static string CantCharge {
            get {
                return ResourceManager.GetString("CantCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultando las cuentas de los bancos..
        /// </summary>
        public static string ConsultingBanksAccounts {
            get {
                return ResourceManager.GetString("ConsultingBanksAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo esta vacio !.
        /// </summary>
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo que se quiere procesar no se encuentra en la ruta..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta que se esta intentando procesar no es de tipo propia o está inactiva..
        /// </summary>
        public static string InvalidAccount {
            get {
                return ResourceManager.GetString("InvalidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta {0} de {1} que se esta intentando procesar no es de tipo propia o está inactiva..
        /// </summary>
        public static string InvalidAccountFileBank {
            get {
                return ResourceManager.GetString("InvalidAccountFileBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró información para {0}, por favor revise y vuelva a intentar. Recuerde que debe existir una hoja con el nombre {0}..
        /// </summary>
        public static string InvalidBankFileNoData {
            get {
                return ResourceManager.GetString("InvalidBankFileNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de registros descritos en el encabezado es diferente a la cantidad de registros que contiene el detalle..
        /// </summary>
        public static string InvalidCountDetail {
            get {
                return ResourceManager.GetString("InvalidCountDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor total de crédito descrito en el encabezado es diferente a la suma de créditos que contiene el detalle..
        /// </summary>
        public static string InvalidCreditValue {
            get {
                return ResourceManager.GetString("InvalidCreditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor total de debito descrito en el encabezado es diferente a la suma de debitos que contiene el detalle..
        /// </summary>
        public static string InvalidDebitValue {
            get {
                return ResourceManager.GetString("InvalidDebitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro un código XM para homologar el código del movimiento..
        /// </summary>
        public static string InvalidXMCode {
            get {
                return ResourceManager.GetString("InvalidXMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro un código XM para homologar el código del movimiento: {0}, para {1}..
        /// </summary>
        public static string InvalidXMCodeBankFile {
            get {
                return ResourceManager.GetString("InvalidXMCodeBankFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finaliza el proceso &quot;Carga Archivo Multicash&quot;..
        /// </summary>
        public static string SaveComplete {
            get {
                return ResourceManager.GetString("SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finaliza el proceso &quot;Cargar Archivo Bancos&quot;..
        /// </summary>
        public static string SaveCompleteBank {
            get {
                return ResourceManager.GetString("SaveCompleteBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia el proceso &quot;Cargar Archivo Bancos&quot;..
        /// </summary>
        public static string StartProcessBank {
            get {
                return ResourceManager.GetString("StartProcessBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando la lectura y escritura del archivo detalle..
        /// </summary>
        public static string StartProcessDetail {
            get {
                return ResourceManager.GetString("StartProcessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando la lectura y escritura del archivo de bancos..
        /// </summary>
        public static string StartProcessFileBank {
            get {
                return ResourceManager.GetString("StartProcessFileBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando la lectura y escritura del archivo encabezado..
        /// </summary>
        public static string StartProcessHead {
            get {
                return ResourceManager.GetString("StartProcessHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia el proceso &quot;Carga Archivo Multicash&quot;..
        /// </summary>
        public static string StartProcessMulticash {
            get {
                return ResourceManager.GetString("StartProcessMulticash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga realizada Con Exito.
        /// </summary>
        public static string SuccessfullCharge {
            get {
                return ResourceManager.GetString("SuccessfullCharge", resourceCulture);
            }
        }
    }
}
