//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WarrantyMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarrantyMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utils.Resources.WarrantyMessages", typeof(WarrantyMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de la garantía debe ser mayor a cero..
        /// </summary>
        public static string AmountEmpty {
            get {
                return ResourceManager.GetString("AmountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entidad financiera no puede ser nula..
        /// </summary>
        public static string BankWarrantyEmpty {
            get {
                return ResourceManager.GetString("BankWarrantyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa no puede ser nula..
        /// </summary>
        public static string CompanyEmpty {
            get {
                return ResourceManager.GetString("CompanyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La moneda solo admite valores COP o USD..
        /// </summary>
        public static string CurrencyAccepted {
            get {
                return ResourceManager.GetString("CurrencyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontrado agentes para la empresa.
        /// </summary>
        public static string ExistsAgentByCompany {
            get {
                return ResourceManager.GetString("ExistsAgentByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha radicado inválida..
        /// </summary>
        public static string FiledDateNotRange {
            get {
                return ResourceManager.GetString("FiledDateNotRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de radicado debe ser mayor que cero..
        /// </summary>
        public static string FiledEmpty {
            get {
                return ResourceManager.GetString("FiledEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio de vigencia debe ser menor a la fecha de fin de vigencia..
        /// </summary>
        public static string InitialValMayorFinalValDate {
            get {
                return ResourceManager.GetString("InitialValMayorFinalValDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de garantizar inicial debe ser menor a la garantizar final de vigencia..
        /// </summary>
        public static string InitialWarMayorFinalWarDate {
            get {
                return ResourceManager.GetString("InitialWarMayorFinalWarDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agente no es distribuidor, comercializador o generador..
        /// </summary>
        public static string IsAgentByCompany {
            get {
                return ResourceManager.GetString("IsAgentByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen revisiones para el tipo de garantía..
        /// </summary>
        public static string JustificationMessage {
            get {
                return ResourceManager.GetString("JustificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no tiene Valor Solicitado.
        /// </summary>
        public static string NoRequstValue {
            get {
                return ResourceManager.GetString("NoRequstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se enviaron números de garantía a liberar.
        /// </summary>
        public static string ReleaseWarrantyNumberEmpty {
            get {
                return ResourceManager.GetString("ReleaseWarrantyNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La garantía tiene aplicaciones pendientes:.
        /// </summary>
        public static string ReleaseWarrantyPending {
            get {
                return ResourceManager.GetString("ReleaseWarrantyPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El firmante no puede ser nulo..
        /// </summary>
        public static string SignatoryEmpty {
            get {
                return ResourceManager.GetString("SignatoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso realizado éxitosamente.
        /// </summary>
        public static string SussefullyProcess {
            get {
                return ResourceManager.GetString("SussefullyProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha fin vigencia inválida..
        /// </summary>
        public static string ValidFinalDateNotRange {
            get {
                return ResourceManager.GetString("ValidFinalDateNotRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inicio vigencia inválida..
        /// </summary>
        public static string ValidInitialDateNotRange {
            get {
                return ResourceManager.GetString("ValidInitialDateNotRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron detalles para la garantia.
        /// </summary>
        public static string WarrantyDetailEmpty {
            get {
                return ResourceManager.GetString("WarrantyDetailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La garantía no existe:.
        /// </summary>
        public static string WarrantyDoesNotExists {
            get {
                return ResourceManager.GetString("WarrantyDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR. Garantia.
        /// </summary>
        public static string WarrantyError {
            get {
                return ResourceManager.GetString("WarrantyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR. &quot;, &quot;No se encontro la garantia número:.
        /// </summary>
        public static string WarrantyNumberDoesntExist {
            get {
                return ResourceManager.GetString("WarrantyNumberDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR., El valor aplicado:.
        /// </summary>
        public static string WarrantyValueApliedPart1 {
            get {
                return ResourceManager.GetString("WarrantyValueApliedPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , es mayor al valor al valor del monto a modificar:.
        /// </summary>
        public static string WarrantyValueApliedPart2 {
            get {
                return ResourceManager.GetString("WarrantyValueApliedPart2", resourceCulture);
            }
        }
    }
}
