//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuerysResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuerysResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infraestructure.Core.Resources.QuerysResources", typeof(QuerysResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Report].[CalculateCustodyAccountPerformanceJob].
        /// </summary>
        internal static string CalculateCustodyAccountPerformanceJob {
            get {
                return ResourceManager.GetString("CalculateCustodyAccountPerformanceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Conciliation].[CalculateCustodyAccountPerformance].
        /// </summary>
        internal static string CustodyAccountPerformanceCalculate {
            get {
                return ResourceManager.GetString("CustodyAccountPerformanceCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Payment].[BalanceBankCustody].
        /// </summary>
        internal static string GetBalanceBankCustody {
            get {
                return ResourceManager.GetString("GetBalanceBankCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Report].[BalanceAccountCustody].
        /// </summary>
        internal static string GetCompanyBalanceCustody {
            get {
                return ResourceManager.GetString("GetCompanyBalanceCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Report].[GetCustodyAccountPerformance].
        /// </summary>
        internal static string GetCustodyAccountPerformance {
            get {
                return ResourceManager.GetString("GetCustodyAccountPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Report].[GetCustodyAccountPerformanceDetail].
        /// </summary>
        internal static string GetCustodyAccountPerformanceDetail {
            get {
                return ResourceManager.GetString("GetCustodyAccountPerformanceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [contabilidad].[CustodyAccountsBank].
        /// </summary>
        internal static string GetCustodyAccountsBank {
            get {
                return ResourceManager.GetString("GetCustodyAccountsBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Conciliation].[spGetImportsPerformanceCalculation].
        /// </summary>
        internal static string GetImportsPerformanceCalculation {
            get {
                return ResourceManager.GetString("GetImportsPerformanceCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Conciliation].[spGetImportsPerformanceCalculationDistribution].
        /// </summary>
        internal static string GetImportsPerformanceCalculationDistribution {
            get {
                return ResourceManager.GetString("GetImportsPerformanceCalculationDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Conciliation].[spGetImportsPerformanceCalculationPivot].
        /// </summary>
        internal static string GetImportsPerformanceCalculationPivot {
            get {
                return ResourceManager.GetString("GetImportsPerformanceCalculationPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Report].[GetInteReteCompanyCustodyAccount].
        /// </summary>
        internal static string GetInteReteCompanyCustodyAccount {
            get {
                return ResourceManager.GetString("GetInteReteCompanyCustodyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Report].[GetInteReteCompanyCustodyCompany].
        /// </summary>
        internal static string GetInteReteCompanyCustodyCompany {
            get {
                return ResourceManager.GetString("GetInteReteCompanyCustodyCompany", resourceCulture);
            }
        }
    }
}
